[tool.poetry]
name = "miles-app-demo"
version = "0.1.0"
description = ""
authors = ["xiazhiqiang <xiazhiqiangcuc@126.com>"]
readme = "README.md"
packages = [{ include = "app_demo", from = "src" }]

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.dev.dependencies]
miles-mod-demo = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
