[tool.poetry]
name = "miles_demo"
version = "0.1.0"
description = ""
authors = ["xiazhiqiang <xiazhiqiangcuc@126.com>"]
readme = "README.md"
packages = [{ include = "demo", from = "src" }]

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
