[tool.poetry]
name = "miles-mod-demo"
version = "0.1.2"
description = ""
authors = ["xiazhiqiang <xiazhiqiangcuc@126.com>"]
readme = "README.md"
packages = [
  { include = "mod_demo", from = "src" },
  { include = "mod_demo2", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
