[tool.poetry]
name = "gradio-demo"
version = "0.1.0"
description = ""
authors = ["xiazhiqiang <xiazhiqiangcuc@126.com>"]
readme = "README.md"
packages = [{include = "gradio_demo", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
orjson = "3.8.12"
gradio = "4.x"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
